CREATE DATABASE IF NOT EXISTS monitor_viagens CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE monitor_viagens;
CREATE TABLE IF NOT EXISTS usuarios (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(120) NOT NULL,
 email VARCHAR(180) NOT NULL UNIQUE,
 telefone VARCHAR(25) NOT NULL UNIQUE,
 senha VARCHAR(255) NOT NULL,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS viagens (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 origem VARCHAR(180) NOT NULL,
 destino VARCHAR(180) NOT NULL,
 data_ida DATE NOT NULL,
 data_volta DATE NULL,
 criada_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_viagens_usuario FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS lugares_favoritos (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 nome VARCHAR(180) NOT NULL,
 cidade VARCHAR(180) NOT NULL DEFAULT '',
 tipo VARCHAR(60) NOT NULL DEFAULT 'lugar',
 latitude DOUBLE NULL,
 longitude DOUBLE NULL,
 lista VARCHAR(20) NOT NULL DEFAULT 'favorito',
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_favoritos_usuario (usuario_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alertas_preco (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 destino VARCHAR(180) NOT NULL,
 tipo VARCHAR(40) NOT NULL DEFAULT 'pacote',
 preco_alvo DECIMAL(12,2) NOT NULL,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_alertas_usuario (usuario_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS itens_carrinho (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 categoria VARCHAR(40) NOT NULL,
 nome VARCHAR(220) NOT NULL,
 quantidade INT NOT NULL DEFAULT 1,
 preco_unitario DECIMAL(12,2) NOT NULL DEFAULT 0,
 total DECIMAL(12,2) NOT NULL DEFAULT 0,
 origem VARCHAR(40) NOT NULL DEFAULT 'simulado',
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_carrinho_usuario (usuario_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS pedidos_orcamento (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 total DECIMAL(12,2) NOT NULL DEFAULT 0,
 status VARCHAR(30) NOT NULL DEFAULT 'planejamento',
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_pedidos_usuario (usuario_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS itens_roteiro (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 data DATE NOT NULL,
 horario VARCHAR(5) NOT NULL DEFAULT '09:00',
 titulo VARCHAR(180) NOT NULL,
 tipo VARCHAR(50) NOT NULL DEFAULT 'atividade',
 latitude DOUBLE NULL,
 longitude DOUBLE NULL,
 notas VARCHAR(500) NOT NULL DEFAULT '',
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_roteiro_usuario (usuario_id),
 INDEX idx_roteiro_data (data)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS roteiros (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 destino VARCHAR(180) NOT NULL,
 data_inicio DATE NOT NULL,
 dias INT NOT NULL,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_roteiros_usuario (usuario_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS roteiro_itens (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 roteiro_id INT UNSIGNED NOT NULL,
 dia INT NOT NULL,
 horario_inicio VARCHAR(5) NOT NULL DEFAULT '12:00',
 horario_fim VARCHAR(5) NOT NULL DEFAULT '13:00',
 titulo VARCHAR(180) NOT NULL,
 tipo VARCHAR(50) NOT NULL DEFAULT 'atividade',
 latitude DOUBLE NULL,
 longitude DOUBLE NULL,
 notas VARCHAR(500) NOT NULL DEFAULT '',
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(roteiro_id) REFERENCES roteiros(id) ON DELETE CASCADE,
 INDEX idx_roteiro_itens_roteiro (roteiro_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS roteiro_membros (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 roteiro_id INT UNSIGNED NOT NULL,
 usuario_id INT UNSIGNED NOT NULL,
 papel VARCHAR(20) NOT NULL DEFAULT 'membro',
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(roteiro_id) REFERENCES roteiros(id) ON DELETE CASCADE,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 UNIQUE KEY uq_roteiro_membro (roteiro_id, usuario_id),
 INDEX idx_roteiro_membros_usuario (usuario_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS viagens_grupo (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT UNSIGNED NOT NULL,
 nome VARCHAR(180) NOT NULL,
 destino VARCHAR(180) NOT NULL,
 data_inicio DATE NULL,
 dias INT NOT NULL DEFAULT 1,
 descricao VARCHAR(500) NOT NULL DEFAULT '',
 token VARCHAR(64) NOT NULL UNIQUE,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_viagens_grupo_usuario (usuario_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS viagens_grupo_membros (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 grupo_id INT UNSIGNED NOT NULL,
 usuario_id INT UNSIGNED NOT NULL,
 papel VARCHAR(20) NOT NULL DEFAULT 'membro',
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(grupo_id) REFERENCES viagens_grupo(id) ON DELETE CASCADE,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 UNIQUE KEY uq_grupo_membro (grupo_id, usuario_id),
 INDEX idx_grupo_membros_usuario (usuario_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS viagens_grupo_itens (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 grupo_id INT UNSIGNED NOT NULL,
 usuario_id INT UNSIGNED NOT NULL,
 categoria VARCHAR(50) NOT NULL DEFAULT 'atividade',
 nome VARCHAR(220) NOT NULL,
 quantidade INT NOT NULL DEFAULT 1,
 preco DECIMAL(12,2) NOT NULL DEFAULT 0,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(grupo_id) REFERENCES viagens_grupo(id) ON DELETE CASCADE,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
 INDEX idx_grupo_itens_grupo (grupo_id)
) ENGINE=InnoDB;
